// Regenerates src/react-app/assets.ts and src/react-app/styles.ts.
//
// Both are checked in, because they are what the app imports. They exist
// because this template is bundled by rolldown with no Vite plugins (see
// README), where `import logo from "./react.svg"` and `import "./index.css"`
// are unresolved modules rather than assets.
//
// The SVGs and the CSS remain the sources of truth. Edit those, then:
//
//   node scripts/gen-assets.mjs
//
// Needs Node, so it runs on a developer machine rather than as part of the
// build. That is fine: the generated files are committed, and nothing
// regenerates them at build time.

import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");

const SVGS = {
	reactLogo: "src/react-app/assets/react.svg",
	honoLogo: "src/react-app/assets/hono.svg",
	cloudflareLogo: "src/react-app/assets/Cloudflare_Logo.svg",
	viteLogo: "public/vite.svg",
};

const STYLES = ["src/react-app/index.css", "src/react-app/App.css"];

const GENERATED = "// Generated by scripts/gen-assets.mjs — do not edit by hand.";

function genAssets() {
	const out = [
		GENERATED,
		"//",
		"// SVG imports as data URIs. Vite resolves these with its asset plugin;",
		"// rolldown on its own does not, so they are inlined here and the imports",
		"// stay plain ESM. The rendered page is identical.",
		"",
	];
	for (const [name, rel] of Object.entries(SVGS)) {
		const b64 = readFileSync(join(root, rel)).toString("base64");
		out.push(`/** ${rel} */`, `export const ${name} =`, `\t"data:image/svg+xml;base64,${b64}";`, "");
	}
	writeFileSync(join(root, "src/react-app/assets.ts"), out.join("\n"));
}

function genStyles() {
	const css = STYLES.map((rel) => `/* ${rel.split("/").pop()} */\n${readFileSync(join(root, rel), "utf8")}`).join("\n");
	// A backtick or a `${` would end the String.raw block early and produce a
	// file that fails to parse a long way from the offending character.
	if (/[`]|\$\{/.test(css)) throw new Error("CSS contains a backtick or ${ — needs escaping");
	const out = [
		GENERATED,
		"//",
		"// The stylesheet as a string, injected into <head> by main.tsx. Same",
		"// reason as assets.ts: `import \"./index.css\"` is a Vite plugin feature.",
		"// index.css and App.css are still the sources.",
		"",
		"export const css = String.raw`",
		css + "`;",
		"",
	];
	writeFileSync(join(root, "src/react-app/styles.ts"), out.join("\n"));
}

genAssets();
genStyles();
console.log("wrote src/react-app/assets.ts and src/react-app/styles.ts");
