// Regenerates src/react-app/assets.ts.
//
// It is checked in, because it is what the app imports. It exists because this
// template is bundled by rolldown with no Vite plugins, where
// `import logo from "./react.svg"` is an unresolved module rather than an asset.
//
// CSS needs no such workaround: `import "./index.css"` is handled, extracted to
// a hashed stylesheet and linked from the document. Only SVG imports are still
// inlined here.
//
// The SVGs remain the source of truth. Edit those, then:
//
//   node scripts/gen-assets.mjs
//
// Needs Node, so it runs on a developer machine rather than as part of the
// build. That is fine: the generated files are committed, and nothing
// regenerates them at build time.

import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");

const SVGS = {
	reactLogo: "src/react-app/assets/react.svg",
	honoLogo: "src/react-app/assets/hono.svg",
	cloudflareLogo: "src/react-app/assets/Cloudflare_Logo.svg",
	viteLogo: "public/vite.svg",
};

const GENERATED = "// Generated by scripts/gen-assets.mjs — do not edit by hand.";

function genAssets() {
	const out = [
		GENERATED,
		"//",
		"// SVG imports as data URIs. Vite resolves these with its asset plugin;",
		"// rolldown on its own does not, so they are inlined here and the imports",
		"// stay plain ESM. The rendered page is identical.",
		"",
	];
	for (const [name, rel] of Object.entries(SVGS)) {
		const b64 = readFileSync(join(root, rel)).toString("base64");
		out.push(`/** ${rel} */`, `export const ${name} =`, `\t"data:image/svg+xml;base64,${b64}";`, "");
	}
	writeFileSync(join(root, "src/react-app/assets.ts"), out.join("\n"));
}

genAssets();
console.log("wrote src/react-app/assets.ts");
